import {StyleSheet, Dimensions} from 'react-native';
import COLORS from '../../../assets/colors';
import TYPOGRAPHY from '../../../assets/typography';

const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    position: 'relative',
  },
  logoContainer: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.25,
    alignItems: 'center',
  },
  appLogo: {
    width: 140,
    height: 140,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FE3501',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: {width: 0, height: 8},
    elevation: 10,
  },
  logoInnerDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FCD34D',
  },
  headerContainer: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.25 + 170,
    alignItems: 'center',
  },
  welcomeText: {
    fontFamily: TYPOGRAPHY.fontFamilyBold,
    fontSize: TYPOGRAPHY.size.heading,
    fontWeight: '700',
    lineHeight: TYPOGRAPHY.lineHeight.heading,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: '#1c1c1c',
  },
  subtitleText: {
    fontFamily: TYPOGRAPHY.fontFamily,
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: '400',
    lineHeight: TYPOGRAPHY.lineHeight.xl,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.textSecondary,
    marginTop: 6,
  },
  bottomButtonsContainer: {
    position: 'absolute',
    bottom: 80,
    width: '100%',
    alignItems: 'center',
  },
  loginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '80%',
    height: 58,
    borderRadius: 9999,
    backgroundColor: COLORS.secondaryBackground,
    marginVertical: 8,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonText: {
    fontFamily: TYPOGRAPHY.fontFamilyMedium,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: '600',
    lineHeight: TYPOGRAPHY.lineHeight.md,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    marginLeft: 12,
    color: '#1c1c1c',
  },
  buttonIcon: {
    marginRight: 8,
  },
  arrowCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.brandPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowText: {
    fontFamily: TYPOGRAPHY.fontFamily,
    fontSize: TYPOGRAPHY.size.xxl,
    fontWeight: '900',
    color: COLORS.white,
    marginLeft: 2,
  },
  agreementText: {
    fontFamily: TYPOGRAPHY.fontFamily,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: '400',
    lineHeight: TYPOGRAPHY.lineHeight.sm,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    position: 'absolute',
    bottom: 30,
    textAlign: 'center',
    color: COLORS.textSecondary,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingContainer: {
    backgroundColor: COLORS.white,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 200,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
  },
  loadingText: {
    color: '#1c1c1c',
    marginTop: 12,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: TYPOGRAPHY.fontFamilyMedium,
  },
});

export default styles;
